### PR TITLE
fix: Add translation support for closing window

### LINKED ISSUE #509: (Front) Make header text in closing.html a translatable string
**Describe the bug**
The text displayed when quitting Mapeo is currently hard-coded and not available as a translatable string. See: https://github.com/digidem/mapeo-desktop/blob/master/static/closing.html#L46

Captura de Tela 2021-07-21 às 1 50 07 PM
 
**Mapeo Version:**
 - Desktop 5.4.0-beta.15 

Points: 8

### PR DESCRIPTION
**Pull request by achou11**
Closes #509 

Alternative approach to #637 that only relies on IPC calls

Preview:

509-closing-window-i18n

### CODE REVIEW

File: src/main/index.js [hunk 1]
```diff
@@ -197,6 +197,15 @@ async function startup ({
...
       if (winMain && winMain.webContents) {
         winMain.webContents.send.apply(winMain.webContents, args)
+
+        if (
+          winClosing &&
+          winClosing.webContents &&
+          args[0].startsWith('CLOSING:')
+        ) {
+          winClosing.webContents.send.apply(winClosing.webContents, args)
+        }
```
Comment (achou11) [inline src/main/index.js:207]: kind of hacky but there wasn't a straightforward way of refactoring these IPC wrappers to support multiple windows.

**Review by ErikSin — APPROVED** [review]
