### PR TITLE
fix: only one window at a time during startup.

### LINKED ISSUE #283: When Mapeo loads, there's a big white screen
**Describe the bug**
When Mapeo loads, there's a big white screen and it looks like there is something wrong with it.

**Can you do the same thing twice?**
Yes, this happens every time you open Mapeo.

**Expected behavior**
The splash screen should replace the empty white screen and the white screen should be invisible upon load.

**Desktop:**
 - OS: All OSs

### PR DESCRIPTION
**Pull request by okdistribute**
fixes #283

### Contributor checklist:

- [x] My contribution is **not** related to translations. _Please submit translation changes via our [Mapeo Crowdin project](https://crowdin.com/project/mapeo-desktop)_
- [x] My commits are in nice logical chunks with [good commit messages](http://chris.beams.io/posts/git-commit/)
- [x] I have walked through the [QA Manual Testing
  Script](https://github.com/digidem/mapeo-desktop/blob/master/docs/testing.md) and updated it if necessary.
- [x] If my changes depend upon an update to a dependency, I have updated the package-lock.json file using `npm install --package-lock`
- [x] My changes have been tested with the [mobile app](https://github.com/digidem/mapeo-mobile/releases). 
- [x] My changes are ready to be shipped to users on Windows, Mac, and Linux

### Description

Tested this on my linux laptop.

This bug was introduced with the new window state manager.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -282,6 +282,9 @@ function notifyReady (done) {
       var IS_TEST = process.env.NODE_ENV === 'test'
       if (IS_TEST) win.setSize(1000, 800, false)
       if (argv.debug) win.webContents.openDevTools()
+
+      win.maximize()
+      win.setFullScreen(true)
```
Comment (marcoautiero) [inline index.js]: I would avoid to call win.setFullScreen(true)
it sets the app...fullscreen (here on ubuntu) and I don't think is the desired behaviour

Comment (okdistribute) [reply index.js]: You're right good catch! thanks!
