### PR TITLE
fix: only display the first 5 character of the project secret key

### LINKED ISSUE #414: Secure project key fully displays in sync screen
**Describe the bug**
displays secrey key

**Expected behavior**
Preferred: Configuration name and version displays 
Ok: only display first 5 Characters of key followed by *****

**Screenshots**
Screen Shot 2020-09-02 at 1 45 54 PM

 
**Mapeo Version:**
 - Desktop v5.4.0.beta7

### PR DESCRIPTION
**Pull request by poga**
### First time contributor checklist:

- [X] I have read the [README](https://github.com/digidem/mapeo-desktop/blob/master/README.md) 

### Contributor checklist:

- [X] My contribution is **not** related to translations. _Please submit translation changes via our [Mapeo Crowdin project](https://crowdin.com/project/mapeo-desktop)_
- [X] My commits are in nice logical chunks with [good commit messages](http://chris.beams.io/posts/git-commit/)
- [X] I have walked through the [QA Manual Testing
  Script](https://github.com/digidem/mapeo-desktop/blob/master/docs/testing.md) and updated it if necessary.
- [X] If my changes depend upon an update to a dependency, I have updated the package-lock.json file using `npm install --package-lock`
- [X] My changes have been tested with the [mobile app](https://github.com/digidem/mapeo-mobile/releases). 
- [X] My changes are ready to be shipped to users on Windows, Mac, and Linux using the production version of the application built with electron-builder.

### Description

Avoid displaying full secret key on the synchronize UI. Fix #414 . 

Tested on MacOS 10.14.6.

I agree with #414 that displaying other configuration names and versions would be preferable and helps user diagnose their issues. Any suggestion on what should also be displayed?

### CODE REVIEW

**Comment by poga** [comment]
Hmm Looks like the code signing failed in the github action. Not sure what caused that 😕

**Comment by okdistribute** [comment]
This is great, thanks @poga! The code signing won't work on forks; someone tried to fix it but I guess it didn't work. This will make it into the 5.4 release. Thanks again!

**Comment by okdistribute** [comment]
>  I agree with #414 that displaying other configuration names and versions would be preferable and helps user diagnose their issues. Any suggestion on what should also be displayed?

I also agree on this point! @jencastrodoesstuff and I were discussing having the 'dataset_id' visible as well, although we haven't been able to talk about what it would ideally look like quite yet. The dataset_id is also not available to the frontend either, so that would need to be fetched too.

**Comment by gmaclennan** [comment]
> Hmm Looks like the code signing failed in the github action. Not sure what caused that 😕

Yes code signing relies on our signing key encoded as a Github secret, which necessarily is not available to PRs (otherwise anybody could create a signed version of Mapeo with their own code). Would be good to avoid failure of CI in this case though.

> I also agree on this point! @jencastrodoesstuff and I were discussing having the 'dataset_id' visible as well

Since [mapeo-settings-builder@2.10.0](https://github.com/digidem/mapeo-settings-builder/blob/master/CHANGELOG.md#2100-2020-03-04) (2020-03-04) the `metadata.json` file in a mapeo config includes [`name` and `version` properties](https://github.com/digidem/mapeo-settings-builder#usage). These would be the most useful to display. Mapeo Mobile exposes the name and version of the config file in the settings screen, the API endpoint already exists: https://github.com/digidem/mapeo-mobile/blob/c7df1fd798a5587d6444cde9127752e1b238fddc/src/frontend/api.js#L267

File: src/renderer/components/SyncView/SyncFooter.js [hunk 1]
```diff
@@ -23,7 +25,9 @@ const SyncFooter = () => {
       <Toolbar>
         <div className={cx.titleBar}>
           <Typography component='h2' className={cx.title}>
-            {encryptionKey}
+            {encryptionKey
+             ? `${encryptionKey.slice(0, visibleKeyLength)}${'*'.repeat(encryptionKey.length - visibleKeyLength)}`
```
Comment (gmaclennan) [inline src/renderer/components/SyncView/SyncFooter.js:29]: I don't think we need to fill `*` to the length of the key. It could cause UI issues (string too long) especially if the use has increased text size. I see in [mobile](https://github.com/digidem/mapeo-mobile/blob/c7df1fd798a5587d6444cde9127752e1b238fddc/src/frontend/screens/SyncModal/SyncView.js#L140) it was pretty random, I just chose 10 `*`, maybe let's do that here for good measure. At some point the encryption key could grow and we don't want a 50-char string here.

**Review by gmaclennan — CHANGES_REQUESTED** [review]
Thanks for this @poga! Awesome.

**Comment by okdistribute** [comment]
>  Since mapeo-settings-builder@2.10.0 (2020-03-04) the metadata.json file in a mapeo config includes name and version properties. These would be the most useful to display. Mapeo Mobile exposes the name and version of the config file in the settings screen, the API endpoint already exists: digidem/mapeo-mobile@c7df1fd/src/frontend/api.js#L267

@poga if you have any time to work on this extra piece, let us know -- otherwise, I can add this in a separate PR later and we can merge yours with the small tweak of using a fixed number of `*` characters.

Thanks for your contribution

File: src/renderer/components/SyncView/SyncFooter.js (hunk 1 above)
Comment (poga) [reply src/renderer/components/SyncView/SyncFooter.js]: Totally agree :) fixed in https://github.com/digidem/mapeo-desktop/pull/419/commits/ddd4d386b7b23f58b7a360f102825ada171a0f79

**Comment by poga** [comment]
Thanks for all the feedbacks! I've followed the suggestion and added additional metadata on screen. Here's how it looks like:

螢幕快照 2020-09-11 11 47 11

Since there's no style guide (yet?) for `mapeo-desktop`. I only added minimal styling for the footer. Feel free to modify it as you like. 😄

File: src/renderer/components/SyncView/SyncFooter.js [hunk 2]
```diff
@@ -23,7 +28,13 @@ const SyncFooter = () => {
...
         <div className={cx.titleBar}>
           <Typography component='h2' className={cx.title}>
-            {encryptionKey}
+            {[metadata ? metadata.name : '',
+              metadata ? metadata.version : ''].join(' ')}
+          </Typography>
+          <Typography component='h2' className={cx.subTitle}>
+            {encryptionKey
+              ? `${encryptionKey.slice(0, visibleKeyLength)}${'*'.repeat(10)}`
+              : ''}
```
Comment (okdistribute) [inline src/renderer/components/SyncView/SyncFooter.js:37]: Should this be 'MAPEO' if there is no encryptionKey, to match the mobile app?
Otherwise LGTM!

Comment (poga) [reply src/renderer/components/SyncView/SyncFooter.js]: Fixed in https://github.com/digidem/mapeo-desktop/pull/419/commits/d1bbd650117dc6652921fb7f0bcb3b1e2f751e4d to match the mobile app.

螢幕快照 2020-09-11 13 04 24
