### PR TITLE
fix: update to electron 9.1.2

### LINKED ISSUE #387: Update to electron >=7
There's a security vulnerability in Electron 6, so we should update to the latest version that also supports node 12.x.

When we upgrade we should also update mapeo/core and related libraries to be automatically tested on the same node version supported by electron.

### PR DESCRIPTION
**Pull request by okdistribute**
fixes #387

### CODE REVIEW

File: src/renderer/components/MapEditor/index.js [hunk 1]
```diff
@@ -126,7 +126,9 @@ const MapEditor = () => {
       var saved = history.toJSON()
       id.current.flush()
       if (saved) history.fromJSON(saved)
-      ipcRenderer.send('zoom-to-data-get-centroid', 'node', zoomToData)
+      api.zoomToData('node', (_, loc) => {
```
Comment (okdistribute) [inline src/renderer/components/MapEditor/index.js:129]: This is now throwing an error because you can't send functions as a callback to `ipcRenderer.send` anymore, but we have the same function available in `ipc`
